"""ArkBot / ArkAgent 模板模組 — 統一匯出所有模板常數"""

# ── ArkBot 原有模板 ──
from .entry import BOT_MAIN_PY, TELEGRAM_ENTRY_PY, WEB_SERVER_PY, WEB_ENTRY_PY, WEB_INDEX_HTML, CLI_ENTRY_PY, DASHBOARD_HUB_HTML, MAIN_PY
from .core import CORE_PY, INTENT_ROUTER_PY, GEMINI_CANVAS_SKILL_PY, DASHBOARD_SKILL_PY, CRAWLER_SKILL_PY, FORMAT_UTILS_PY
from .decision import SKILL_REGISTRY_PY, SKILL_RESOLVER_PY, SKILL_PROMPT_PY, HYBRID_ROUTER_PY
from .runtime import (
    EXECUTOR_PY, SCHEDULER_PY,
    # Runtime Adapter 模板
    RUNTIME_ADAPTER_INIT_PY, RUNTIME_ADAPTER_BASE_PY,
    PYTHON_ADAPTER_PY, MCP_ADAPTER_PY, AI_ADAPTER_PY, COMPOSITE_ADAPTER_PY,
)
from .skills import (
    SKILL_PKG_CRAWLER_PY,
    SKILL_PKG_CHAT_PY,
    SKILL_PKG_DASHBOARD_PY,
    SAMPLE_REVENUE_JSON, SAMPLE_SLOTS_JSON, SAMPLE_FISH_JSON,
    # ArkAgent YAML 版
    SKILL_PKG_CRAWLER_YAML, SKILL_PKG_CHAT_YAML, SKILL_PKG_DASHBOARD_YAML,
    # ArkAgent Notify Skill
    SKILL_PKG_NOTIFY_YAML, SKILL_PKG_NOTIFY_PY,
    # Gemini Canvas Skill Package
    SKILL_PKG_CANVAS_YAML, SKILL_PKG_CANVAS_PY,
    # Composite Workflow Skill Package
    SKILL_PKG_DAILY_REPORT_YAML,
    # AIBI Skill Package（MCP / AI / Composite）
    SKILL_PKG_SQL_QUERY_YAML, SKILL_PKG_BIGQUERY_QUERY_YAML,
    SKILL_PKG_MSSQL_QUERY_YAML,
    SKILL_PKG_KPI_ANALYZER_YAML, SKILL_PKG_KPI_ANALYZER_PROMPT,
    SKILL_PKG_ANOMALY_REPORT_YAML,
)
from .tests import (
    TEST_BASIC_PY, TEST_SKILL_REGISTRY_PY, TEST_SKILL_RESOLVER_PY, TEST_EXECUTOR_PY,
    # ArkAgent 新增測試
    TEST_KERNEL_PY, TEST_MEMORY_PY, TEST_TOOLS_PY, TEST_SPECS_PY,
    # 平台級架構新增測試
    TEST_DOMAIN_CONTROLLER_PY, TEST_SYSTEM_CONTROLLER_PY,
    TEST_PYTHON_CONTROLLER_PY, TEST_MCP_CONTROLLER_PY,
    TEST_PLANNER_PY, TEST_GATEWAY_PY,
)
from .config import (
    START_BAT, SCHEDULES_JSON, ENV_EXAMPLE, REQUIREMENTS_TXT,
    INIT_DB_PY, BOT_TEST_GUIDE,
    # ArkAgent 設定
    ARKAGENT_START_BAT, ARKAGENT_ENV_EXAMPLE, ARKAGENT_REQUIREMENTS_TXT,
    # Telegram 路由設定
    TELEGRAM_CONFIG_JSON,
)

# ── ArkAgent OS 新增模板 ──
from .specs import (
    SKILL_SCHEMA_JSON, AGENT_SCHEMA_JSON, RUNTIME_SCHEMA_JSON,
    SKILL_EXAMPLE_YAML, AGENT_EXAMPLE_YAML, RUNTIME_YAML,
    VALIDATE_SPECS_PY, ARCH_REVIEWER_PROMPT, REVIEW_ARCHITECTURE_PY,
)
from .kernel import (
    AGENT_BASE_PY, KERNEL_CONFIG_PY, KERNEL_LOGGER_PY,
    SPEC_LOADER_PY, KERNEL_INIT_PY,
)
from .memory import SHORT_TERM_PY, LONG_TERM_PY, MEMORY_INIT_PY
from .tools import GATEWAY_PY, GEMINI_TOOL_PY, TELEGRAM_TOOL_PY, WEB_TOOL_PY, TOOLS_INIT_PY

# ── 平台級架構新增模板 ──
from .controller import (
    MCP_CONFIG_JSON,
    CONTROLLER_INIT_PY, DOMAIN_CONTROLLER_PY,
    SYSTEM_CONTROLLER_PY, PYTHON_CONTROLLER_PY, MCP_CONTROLLER_PY,
)
from .planner import (
    PLANNER_INIT_PY, EXECUTION_PLAN_PY, SKILL_PLANNER_PY,
)
from .gateway import (
    GATEWAY_INIT_PY, GATEWAY_AUTH_PY, GATEWAY_RATE_LIMITER_PY,
    GATEWAY_WEBSOCKET_PY, GATEWAY_APP_PY,
)
